<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TheSingularityWorkshop.SingularityHub</RootNamespace>
    <AssemblyName>SingularityHub.Abstractions</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TheSingularityWorkshop.FSM_API" Version="1.0.13" />
    <PackageReference Include="TheSingularityWorkshop.ProtocolAi" Version="0.1.0-alpha.2" />
  </ItemGroup>
</Project>
