<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>TheSingularityWorkshop.SingularityHub</RootNamespace>
    <AssemblyName>SingularityHub.Abstractions</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TheSingularityWorkshop.FSM_API" Version="1.0.13" />
    <PackageReference Include="TheSingularityWorkshop.FSM_COS" Version="0.1.0-alpha.5"" />
    <PackageReference Include="TheSingularityWorkshop.FSM_Serialization" Version="0.1.0-alpha.2" />
  </ItemGroup>
</Project>
