name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      - development
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: >-
      (github.event_name == 'push' &&
      (github.ref == 'refs/heads/master' || contains(github.event.head_commit.message, '[deploy-public]'))) ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
          lfs: false

      - name: Restore WebPage
        run: dotnet restore TheSingularityWorkshop/TheSingularityWorkshop.csproj

      - name: Publish WebPage
        run: >
          dotnet publish TheSingularityWorkshop/TheSingularityWorkshop.csproj
          --configuration Release
          --no-restore

      - name: Deploy prebuilt WebPage
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_GROUND_09F542010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./TheSingularityWorkshop/bin/Release/net8.0/publish/wwwroot"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_GROUND_09F542010 }}
          action: "close"
